# اسم سير العمل
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # هذه هي الخطوة التي تضيف فيها الوكيل
      - name: Set up proxy for Gradle
        run: |
          echo "systemProp.http.proxyHost=38.127.172.60" >> gradle.properties
          echo "systemProp.http.proxyPort=24171" >> gradle.properties
          echo "systemProp.https.proxyHost=38.127.172.60" >> gradle.properties
          echo "systemProp.https.proxyPort=24171" >> gradle.properties
      
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      # هذه الخطوة ستقوم بإنشاء ملف APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # هذه الخطوة ستقوم بتحميل ملف APK كـ "artifact"
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
