# اسم سير العمل
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # هذه الخطوة هي التي تضيف إعدادات الوكيل
      - name: Set up proxy environment variables
        env:
          HTTP_PROXY: http://your-proxy-host:port
          HTTPS_PROXY: http://your-proxy-host:port
          NO_PROXY: localhost,127.0.0.1,.local
      
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
