# اسم سير العمل
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # هذه هي الخطوة التي تضيف فيها الوكيل
      - name: Set up proxy for Gradle
        run: |
          echo "systemProp.http.proxyHost=your-proxy-host" >> gradle.properties
          echo "systemProp.http.proxyPort=your-proxy-port" >> gradle.properties
          echo "systemProp.https.proxyHost=your-proxy-host" >> gradle.properties
          echo "systemProp.https.proxyPort=your-proxy-port" >> gradle.properties
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
