# اسم سير العمل
name: Build Android App with Proxy

# تحديد الحدث الذي يشغل سير العمل
on:
  push:
    branches:
      - main

# تعريف المهام
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up proxy environment variables
        env:
          HTTP_PROXY: http://your-proxy-host:port
          HTTPS_PROXY: http://your-proxy-host:port
          NO_PROXY: localhost,127.0.0.1,.local

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
